defaults: &defaults
  adapter: postgresql
  host: localhost
  port: 5432
  encoding: unicode
  pool: 5
  username: <%= ENV['ARKEN_DB_USER'] || ENV['USER'] %>
  password: <%= ENV['ARKEN_DB_PASSWORD'] %>
  min_messages: warning

development:
  <<: *defaults
  database: arken_dev

test: &test
  <<: *defaults
  database: arken_test
